### ISSUE TITLE
CryptoJWT with Shibboleth OIDC CSCfi extension

### ISSUE THREAD

**Issue by peppelinux** [IdentityPython/JWTConnect-Python-CryptoJWT#73]
I tried to use cryptojwt to produce some jwks.
That's the command I used (but tried also to do the same via Python CLI)
````
jwkgen --size 2048 --kty RSA --kid defaultRSASign > /opt/shibboleth-idp/credentials/idp-signing-rs.jwk
````
This latter produces a private (Full) key

Otherwise the shib command would be this (produces private-full + public):
````
java -jar /opt/json-web-key-generator-json-web-key-generator-0.7/target/json-web-key-generator-0.7-jar-with-dependencies.jar -t RSA -s 2048 -u sig -i defaultRSASign -p > /opt/shibboleth-idp/credentials/idp-signing-rs.jwk
````

Using JWK from cryptojwt in a ShibIdP test configuration I get this:

````
2020-10-17 17:39:21,062 -  - ERROR [org.geant.idpextension.oidc.profile.spring.factory.BasicJWKCredentialFactoryBean:81] - null: Could not decode KeyFile at file [/opt/shibboleth-idp/credentials/idp-signing-rs.jwk]: {}
java.text.ParseException: Incomplete second private (CRT) representation: The first factor CRT exponent must not be null
	at com.nimbusds.jose.jwk.RSAKey.parse(RSAKey.java:2138)
2020-10-17 17:39:21,063 -  - WARN [net.shibboleth.ext.spring.context.FilesystemGenericApplicationContext:558] - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.UnverifiedRelyingParty' defined in file [/opt/shibboleth-idp/conf/relying-party.xml]: Cannot create inner bean 'OIDC.Keyset$child#6cb48007' of type [org.geant.idpextension.oidc.config.OIDCPublishKeySetConfiguration] while setting bean property 'profileConfigurations' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OIDC.Keyset$child#6cb48007' defined in file [/opt/shibboleth-idp/conf/relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.PublishKeySetSecurityConfiguration' while setting bean property 'securityConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.PublishKeySetSecurityConfiguration' defined in file [/opt/shibboleth-idp/conf/oidc-relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.PublishKeySetSigningConfiguration' while setting bean property 'signatureSigningConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.PublishKeySetSigningConfiguration' defined in file [/opt/shibboleth-idp/conf/oidc-relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.SigningCredentialsToPublish' while setting bean property 'signingCredentials'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.SigningCredentials': Cannot resolve reference to bean 'shibboleth.oidc.DefaultRSSigningCredential' while setting bean property 'sourceList' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.DefaultRSSigningCredential' defined in file [/opt/shibboleth-idp/conf/credentials-oidc.xml]: Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided KeyFile file [/opt/shibboleth-idp/credentials/idp-signing-rs.jwk]; nested exception is java.text.ParseException: Incomplete second private (CRT) representation: The first factor CRT exponent must not be null
2020-10-17 17:39:21,065 -  - ERROR [net.shibboleth.utilities.java.support.service.AbstractReloadableService:182] - Service 'shibboleth.RelyingPartyResolverService': Initial load failed
net.shibboleth.utilities.java.support.service.ServiceException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.UnverifiedRelyingParty' defined in file [/opt/shibboleth-idp/conf/relying-party.xml]: Cannot create inner bean 'OIDC.Keyset$child#6cb48007' of type [org.geant.idpextension.oidc.config.OIDCPublishKeySetConfiguration] while setting bean property 'profileConfigurations' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OIDC.Keyset$child#6cb48007' defined in file [/opt/shibboleth-idp/conf/relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.PublishKeySetSecurityConfiguration' while setting bean property 'securityConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.PublishKeySetSecurityConfiguration' defined in file [/opt/shibboleth-idp/conf/oidc-relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.PublishKeySetSigningConfiguration' while setting bean property 'signatureSigningConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.PublishKeySetSigningConfiguration' defined in file [/opt/shibboleth-idp/conf/oidc-relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.SigningCredentialsToPublish' while setting bean property 'signingCredentials'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.SigningCredentials': Cannot resolve reference to bean 'shibboleth.oidc.DefaultRSSigningCredential' while setting bean property 'sourceList' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.DefaultRSSigningCredential' defined in file [/opt/shibboleth-idp/conf/credentials-oidc.xml]: Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided KeyFile file [/opt/shibboleth-idp/credentials/idp-signing-rs.jwk]; nested exception is java.text.ParseException: Incomplete second private (CRT) representation: The first factor CRT exponent must not be null
	at net.shibboleth.ext.spring.service.ReloadableSpringService.doReload(ReloadableSpringService.java:377)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.UnverifiedRelyingParty' defined in file [/opt/shibboleth-idp/conf/relying-party.xml]: Cannot create inner bean 'OIDC.Keyset$child#6cb48007' of type [org.geant.idpextension.oidc.config.OIDCPublishKeySetConfiguration] while setting bean property 'profileConfigurations' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OIDC.Keyset$child#6cb48007' defined in file [/opt/shibboleth-idp/conf/relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.PublishKeySetSecurityConfiguration' while setting bean property 'securityConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.PublishKeySetSecurityConfiguration' defined in file [/opt/shibboleth-idp/conf/oidc-relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.PublishKeySetSigningConfiguration' while setting bean property 'signatureSigningConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.PublishKeySetSigningConfiguration' defined in file [/opt/shibboleth-idp/conf/oidc-relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.SigningCredentialsToPublish' while setting bean property 'signingCredentials'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.SigningCredentials': Cannot resolve reference to bean 'shibboleth.oidc.DefaultRSSigningCredential' while setting bean property 'sourceList' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.DefaultRSSigningCredential' defined in file [/opt/shibboleth-idp/conf/credentials-oidc.xml]: Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided KeyFile file [/opt/shibboleth-idp/credentials/idp-signing-rs.jwk]; nested exception is java.text.ParseException: Incomplete second private (CRT) representation: The first factor CRT exponent must not be null
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveInnerBean(BeanDefinitionValueResolver.java:389)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'OIDC.Keyset$child#6cb48007' defined in file [/opt/shibboleth-idp/conf/relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.PublishKeySetSecurityConfiguration' while setting bean property 'securityConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.PublishKeySetSecurityConfiguration' defined in file [/opt/shibboleth-idp/conf/oidc-relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.PublishKeySetSigningConfiguration' while setting bean property 'signatureSigningConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.PublishKeySetSigningConfiguration' defined in file [/opt/shibboleth-idp/conf/oidc-relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.SigningCredentialsToPublish' while setting bean property 'signingCredentials'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.SigningCredentials': Cannot resolve reference to bean 'shibboleth.oidc.DefaultRSSigningCredential' while setting bean property 'sourceList' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.DefaultRSSigningCredential' defined in file [/opt/shibboleth-idp/conf/credentials-oidc.xml]: Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided KeyFile file [/opt/shibboleth-idp/credentials/idp-signing-rs.jwk]; nested exception is java.text.ParseException: Incomplete second private (CRT) representation: The first factor CRT exponent must not be null
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.PublishKeySetSecurityConfiguration' defined in file [/opt/shibboleth-idp/conf/oidc-relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.PublishKeySetSigningConfiguration' while setting bean property 'signatureSigningConfiguration'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.PublishKeySetSigningConfiguration' defined in file [/opt/shibboleth-idp/conf/oidc-relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.SigningCredentialsToPublish' while setting bean property 'signingCredentials'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.SigningCredentials': Cannot resolve reference to bean 'shibboleth.oidc.DefaultRSSigningCredential' while setting bean property 'sourceList' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.DefaultRSSigningCredential' defined in file [/opt/shibboleth-idp/conf/credentials-oidc.xml]: Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided KeyFile file [/opt/shibboleth-idp/credentials/idp-signing-rs.jwk]; nested exception is java.text.ParseException: Incomplete second private (CRT) representation: The first factor CRT exponent must not be null
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.PublishKeySetSigningConfiguration' defined in file [/opt/shibboleth-idp/conf/oidc-relying-party.xml]: Cannot resolve reference to bean 'shibboleth.oidc.SigningCredentialsToPublish' while setting bean property 'signingCredentials'; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.SigningCredentials': Cannot resolve reference to bean 'shibboleth.oidc.DefaultRSSigningCredential' while setting bean property 'sourceList' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.DefaultRSSigningCredential' defined in file [/opt/shibboleth-idp/conf/credentials-oidc.xml]: Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided KeyFile file [/opt/shibboleth-idp/credentials/idp-signing-rs.jwk]; nested exception is java.text.ParseException: Incomplete second private (CRT) representation: The first factor CRT exponent must not be null
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.SigningCredentials': Cannot resolve reference to bean 'shibboleth.oidc.DefaultRSSigningCredential' while setting bean property 'sourceList' with key [0]; nested exception is org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.DefaultRSSigningCredential' defined in file [/opt/shibboleth-idp/conf/credentials-oidc.xml]: Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided KeyFile file [/opt/shibboleth-idp/credentials/idp-signing-rs.jwk]; nested exception is java.text.ParseException: Incomplete second private (CRT) representation: The first factor CRT exponent must not be null
	at org.springframework.beans.factory.support.BeanDefinitionValueResolver.resolveReference(BeanDefinitionValueResolver.java:342)
Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'shibboleth.oidc.DefaultRSSigningCredential' defined in file [/opt/shibboleth-idp/conf/credentials-oidc.xml]: Invocation of init method failed; nested exception is org.springframework.beans.FatalBeanException: Could not decode provided KeyFile file [/opt/shibboleth-idp/credentials/idp-signing-rs.jwk]; nested exception is java.text.ParseException: Incomplete second private (CRT) representation: The first factor CRT exponent must not be null
	at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
Caused by: org.springframework.beans.FatalBeanException: Could not decode provided KeyFile file [/opt/shibboleth-idp/credentials/idp-signing-rs.jwk]; nested exception is java.text.ParseException: Incomplete second private (CRT) representation: The first factor CRT exponent must not be null
	at org.geant.idpextension.oidc.profile.spring.factory.BasicJWKCredentialFactoryBean.doCreateInstance(BasicJWKCredentialFactoryBean.java:83)
Caused by: java.text.ParseException: Incomplete second private (CRT) representation: The first factor CRT exponent must not be null
	at com.nimbusds.jose.jwk.RSAKey.parse(RSAKey.java:2138)
````

I tried to generate my jwk with cryptojwt because I'm tring to understand why CSCfi OIDC OP release an access token signed in a way that makes idpy's OIDC rp raise a BadSignature Exception.

This need a more accurate analysis, that' my first footprint

**Comment by peppelinux** [comment]
Works great this way

````
import json
from cryptojwt.jwk.rsa import new_rsa_key
rsa_key = new_rsa_key()
jwk = rsa_key.serialize(private=True)

# public
print(json.dumps(rsa_key.serialize(), indent=2))

````

**Comment by rohe** [comment]
I have to look at this but there really should not be a difference between keys produced by jwkgen and new_rsa_key/serialize .

**Comment by peppelinux** [comment]
Confirmed!

Cscfi needs only public keys, i used cryptojwt succesfully. Just a note, It produces a private Key and I got a good resilt only via python cli. Probably I'll take a deeper look in It and eventually pull a request to extend the tool arguments

**Comment by rohe** [comment]
Ah, OK ! Well jwkgen is expected to produce private keys (which can easily be used to produce the matching public key).
One could imaging producing both a private and a public key as the immediate output.

**Comment by peppelinux** [comment]
In CSCfi guide the keys production Is done with a Java tool, that needs to be compiled with maven, takes dependencies and time. I think that cryptojwt would be the best choice, they Just should know It and how to use it
